services:
  rss_notifier:
    build: .
    container_name: rss_notifier
    restart: always
    volumes:
      - rss_data:/rss_sent.db
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - CHAT_ID=${CHAT_ID}
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}
volumes:
  rss_data: